# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-05 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20171022_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='CONTENT'),
        ),
    ]
