# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-05 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20180606_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=1),
        ),
    ]
