# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-05 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='psttext',
        ),
    ]
