# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-05 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20180606_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='psttext',
            field=models.TextField(default='', verbose_name='내용작성'),
        ),
    ]
