# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-08 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20180606_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='post', verbose_name='사진'),
        ),
    ]
