# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-07 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20180608_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pstdate',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='작성일'),
        ),
    ]
