# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-05 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20171022_1354'),
        ('member', '0004_remove_user_like_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_posts',
            field=models.ManyToManyField(blank=True, related_name='like_posts', to='post.Post'),
        ),
    ]
