# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-07 06:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HW_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psttitle', models.CharField(max_length=30, verbose_name='제목')),
                ('psttext', models.TextField(verbose_name='내용')),
                ('pstdate', models.DateTimeField(auto_now_add=True)),
                ('bphoto', models.ImageField(upload_to='post', verbose_name='사진등록')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
