# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-07 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hw_post',
            name='pstdate',
            field=models.DateTimeField(verbose_name='작성일'),
        ),
    ]
