# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-07 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180607_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hw_post',
            name='bphoto',
            field=models.ImageField(blank=True, null=True, upload_to='post', verbose_name='사진등록'),
        ),
    ]
